### PR TITLE
Remove formulae migrated to homebrew-core

### PR DESCRIPTION
**Pull request by jslee02**
The following formulae migrated to [`homebrew-core`](https://github.com/Homebrew/homebrew-core)! :tada: 
* [console_bridge](https://github.com/Homebrew/homebrew-core/pull/23899)
* [urdfdom_headers](https://github.com/Homebrew/homebrew-core/pull/23901)
* [urdfdom](https://github.com/Homebrew/homebrew-core/pull/23902)

This PR remove those formulae.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks! Not sure what the issue is with our travis testing, @jslee02 any ideas? I don't have time to look into it right this second.

**Comment by jslee02** [comment]
It seems this is because `pyassimp` uses deprecated `:python` according to the test [log](https://travis-ci.org/ros/homebrew-deps/jobs/340158979#L1973).

Let me quickly create a PR following the instruction to see if that works.

**Comment by jslee02** [comment]
@wjwwood It seems Travis is happy now!

**Comment by wjwwood** [comment]
@jslee02 Thanks a lot for iterating on it for me!

**Pull request merged**
